apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  labels:
    app: currency-conversion
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - name: currency-conversion
          image: "{{ .Values.image.name }}:{{ .Values.imageTag | default 1 }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
